const d=JSON.parse(JSON.stringify(window.SPMB_DATA||{}));const form=document.getElementById("editor");const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const fields=["schoolName","tagline","year","heroTitle","formUrl","phone","email","address","heroDescription","welcomeText","heroExtra","registrationDescription","principalName","founderName"];
fields.forEach(n=>{if(form.elements[n])form.elements[n].value=d[n]||""});
["documents","steps","dailyActivities","monthlyActivities","yearlyActivities","programs"].forEach(n=>form.elements[n].value=(d[n]||[]).join("\n"));
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function scheduleUI(){const box=$("#schedule");box.innerHTML="";(d.schedule||[]).forEach((x,i)=>{const r=document.createElement("div");r.className="schedule-row";r.innerHTML=`<input data-s="${i}" data-k="title" placeholder="Nama gelombang" value="${esc(x.title)}"><input data-s="${i}" data-k="date" placeholder="Tanggal" value="${esc(x.date)}"><input data-s="${i}" data-k="benefit" placeholder="Keuntungan" value="${esc(x.benefit)}"><button type="button" class="delete" data-del-s="${i}">×</button>`;box.appendChild(r)});$$("[data-del-s]").forEach(b=>b.onclick=()=>{d.schedule.splice(+b.dataset.delS,1);scheduleUI()})}
scheduleUI();$("#addSchedule").onclick=()=>{d.schedule=d.schedule||[];d.schedule.push({title:"GELOMBANG BARU",date:"Isi tanggal",benefit:"Isi keuntungan"});scheduleUI()};
function mediaUI(){const box=$("#mediaEditor");box.innerHTML="";(d.media||[]).forEach((m,i)=>{const r=document.createElement("div");r.className="media-row";const preview=m.src?`<img class="media-preview" src="${esc(m.src)}" alt="">`:`<div class="media-preview"></div>`;r.innerHTML=`${preview}<input data-mi="${i}" data-mk="title" placeholder="Judul" value="${esc(m.title)}"><input data-mi="${i}" data-mk="caption" placeholder="Keterangan" value="${esc(m.caption)}"><select data-mi="${i}" data-mk="type"><option value="image" ${m.type==="image"?"selected":""}>Foto</option><option value="video" ${m.type==="video"?"selected":""}>Video URL</option></select><button type="button" class="delete" data-del-m="${i}">Hapus</button><input class="wide" data-mi="${i}" data-mk="src" placeholder="URL media atau upload foto di tombol bawah" value="${esc(m.src)}"><label class="wide">Upload Foto (opsional)<input type="file" accept="image/*" data-media-file="${i}"></label>`;box.appendChild(r)});$$("[data-del-m]").forEach(b=>b.onclick=()=>{d.media.splice(+b.dataset.delM,1);mediaUI()});$$("[data-media-file]").forEach(inp=>inp.onchange=e=>{const f=e.target.files[0],i=+e.target.dataset.mediaFile;if(!f)return;if(f.size>5*1024*1024){alert("Foto terlalu besar. Maksimal 5 MB per foto.");return}const reader=new FileReader();reader.onload=()=>{d.media[i].src=reader.result;d.media[i].type="image";mediaUI()};reader.readAsDataURL(f)})}
d.media=d.media||[];mediaUI();$("#addMedia").onclick=()=>{d.media.push({type:"image",src:"",title:"",caption:""});mediaUI()};
$$("[data-file]").forEach(inp=>inp.onchange=e=>{const f=e.target.files[0],key=e.target.dataset.file;if(!f)return;if(f.size>5*1024*1024){alert("Foto terlalu besar. Maksimal 5 MB.");e.target.value="";return}const r=new FileReader();r.onload=()=>{d[key]=r.result;const p=$("#preview-"+key);if(p)p.src=r.result};r.readAsDataURL(f)});
["logo","principalPhoto","founderPhoto","buildingPhoto","barcodePhoto"].forEach(k=>{if(d[k]&&$("#preview-"+k))$("#preview-"+k).src=d[k]});
form.onsubmit=e=>{e.preventDefault();fields.forEach(n=>d[n]=form.elements[n].value);["documents","steps","dailyActivities","monthlyActivities","yearlyActivities","programs"].forEach(n=>d[n]=form.elements[n].value.split("\n").map(x=>x.trim()).filter(Boolean));d.schedule=$$("#schedule .schedule-row").map(r=>({title:r.querySelector('[data-k="title"]').value,date:r.querySelector('[data-k="date"]').value,benefit:r.querySelector('[data-k="benefit"]').value}));d.media=$$("#mediaEditor .media-row").map(r=>({type:r.querySelector('[data-mk="type"]').value,src:r.querySelector('[data-mk="src"]').value,title:r.querySelector('[data-mk="title"]').value,caption:r.querySelector('[data-mk="caption"]').value})).filter(x=>x.src);
const blob=new Blob(["window.SPMB_DATA = "+JSON.stringify(d,null,2)+";"],{type:"application/javascript"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="data.js";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);alert("data.js berhasil dibuat. Upload file tersebut ke repository GitHub, lalu tunggu GitHub Pages memperbarui website.")};
